Refactoring Parser+Auftragsverwaltung
AlexanderNahr/arduino_team_PMES_WS2016 pull request #101
Opened 2017-03-06 22:37 UTC by izabellasandor

Bugfixing, modifications

2017-03-06 22:40 UTC, izabellasandor commented
Was neu ist:
Die Error Nachrichten sind angepasst.
Bug mit dem NewClient ist gelöst.
SIGN_OUT wurde vereinfacht (kein Passwortcheck nötig)
An die App sind nur Nachrichten gesendet, die sie erwartet.
Unterscheidung zwischen einem tatsächlich neuem Client und den zyklischen Meldungen von der App. 

Was noch immer fehlt:
Bestellungen sind noch immer erlaubt vor dem Sign_in.

2017-03-06 22:41 UTC, izabellasandor commented
Bitte testen :)

2017-03-07 02:02 UTC, AlexanderNahr requested changes
Test cases 
['[SIGN_IN%a]', 
 '[SIGN_IN%ilias2017]', 
 '[SIGN_IN%ilias2017]',              '[ORDER%ilias2017%6;1;00244;10342;61130;30534;51221;21413]',
  '[ORDER%a%1;2;11111;22222;33333]'
  '[SIGN_OUT]'  -> KEIN RETURNVALUE
            ]

Received:
*HELLO*[SIGN_IN_RS%0%0%PW_WRONG]

[SIGN_IN_RS%0%0%SUCCESSFUL]

[SIGN_IN_RS%0%0%SUCCESSFUL]

[ORDER_RS%SUCCESSFUL%0%0]

[ORDER_RS%PW_WRONG%1%27]

-> LOGOUT gibt keinen Return value an den client

2017-03-07 02:02 UTC, AlexanderNahr commented on code/integration/Main/Parser.cpp
>    return StringToBeReturned;
Sollte LOGOUT_SUCCESSFUL nicht als return value zugeordnet werden? Ansonsten wird dies nicht an den Client zurueck gesendet.

2017-03-07 07:09 UTC, izabellasandor commented on code/integration/Main/Parser.cpp
>    return StringToBeReturned;
Ich weiß nicht, was wir da zurück senden sollen. Bisher ging einfach der selbe String zurück, der kam. Ich habe ihn aber gelöscht. Ich dachte, da brauchen wir das nicht. Im Protokoll steht auch "No response".

2017-03-07 07:10 UTC, izabellasandor commented on code/integration/Main/Parser.cpp
>    return StringToBeReturned;
Ich weiß nicht, was wir da zurück senden sollen. Bisher ging einfach der selbe String zurück, der kam. Ich habe ihn aber gelöscht. Ich dachte, da brauchen wir das nicht. Im Protokoll steht auch "No response".

2017-03-07 14:23 UTC, AlexanderNahr commented on code/integration/Main/Parser.cpp
>    return StringToBeReturned;
OK, dann habe ich das flasch verstanden! Du hast recht im Dokument steht es nicht!

2017-03-07 14:23 UTC, AlexanderNahr approved these changes

2017-03-07 18:13 UTC, merged