Branch wi fi service
AlexanderNahr/arduino_team_PMES_WS2016 pull request #55
Opened 2017-02-06 22:05 UTC by myhamidi

Für das WLAN Modul, habe ich eine Klasse 'WiFiService' erstellt, die als Header eingebunden werden kann. Wichtig: WiFiService.h  bindet automatisch die SoftwareSerial.h mit ein. SoftwareSerial seperat zu lassen, habe ich technisch leider nicht hinbekommen, sollte aber auch kein Problem sein, da sich alle SoftwareSerial Funktionen einfach durchschieben/routen lassen). 

Folgende (public) Funktionen stehen bisher zur Verfügung:
- **void Init(bool mode)**; --> Damit wird die Routine aktiviert. Wenn mode = false, wird nur die Bidirektional Kommunikation aktiv, bei mode = true wird auf einen String mit [ als Start und ] als Enzeichen gewartet. Der String muss dabei nicht in einem Stück gesendet werden.
- **bool String_Is_Complete();** --> Sobald der String voll ist/ endeckt wurde, gibt diese Funktion true aus
- **String Get_String();** --> Diese Funktion gibt den gefundenen String aus, wenn noch kein String gefunden wurde dann "Test"
- **void ResetString();** --> resetet den String und die Routine. Nach ResetString kann nach einem weiterem String gesucht werden

Der Vorteil von einer Klasse ist wie ich finde, ist dass die gesamte Logik gekapselt in dem WiFiService Objekt steckt. Die Klasse übernimmt alle Aufgaben die irgendwie mit der WLAN Kommunikation zu zun haben. Der Code in der Main Loop beschränkt sich damit auf das Aufrufen von wenigen Funktionen.

Was haltet ihr davon?
Probiert es bitte mal auf der Arduino HW aus, vielleicht vermisst ihr die eine oder andere Funktion noch!

2017-02-06 22:58 UTC, AlexanderNahr commented
Coolio! Klassen sind ok fuer mich! Auch wenn die Sw Serial etc nicht gekapselt sind ist das OK. Der Gedanke dahinter war nur, dass die Hw (Wifly Modul), das String Protokol, und die uController (UARTs) unabhaengig sind. 

Zu den weiteren Methoden:
SendString -> zum senden unseres Antwortstrings
const byte MAX_STRING_LENGTH -> Konstante fuer maximale empfangbare string laenge

2017-02-06 22:59 UTC, AlexanderNahr requested changes

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +// HWtoSWSerial is always active
Method HWtoSWSerial sendet also alles vom PC (HwSerial) an das Wifi Module (SwSerial)?

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +    if (SerialChar == '[')
Mein Verstaendnis war, dass wir keine Start und Stop-Char mehr nehmen. Solange etwas im Buffer ist und < max string length wird von der UART gelesen. Wenn keine charactere mehr ankommen, hoeren wir auf.

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  //Mode "Bidirectional". Just bidirectional Mode between SW and HW Serial.
Was genau meinst du mit Bidirectional mode?

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  if (mode == true && !StringComplete)        {Wait_for_Start_Character();  HWtoSWSerial();}
Ich bin etwas verwirrt was das HWtoSWSerial hier macht. Wenn der StartCharacter gefunde wird, wird es immer noch ausgefuehrt. Wozu?

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/Class_WiFiService.ino
> +  myWiFiService.Init(true);
Anfangs habe ich mich gefragt: "Muss wirklich in jedem loop der Service neu initialisiert werden?" Aber das "Init" steuert einfach den Empfang der Nachrichten?

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.h
> +  int StringLength;
Daraus wuerde ich ein 'byte' machen. Integers sind glaube ich 16 bit auf dem Atmega 328. So sparen wir uns etwas Speicher.

2017-02-06 22:59 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  rxString.reserve(50);
Vermeide "magic numbers", also ersetze 50 durch eine Konstante. Nicht mission critical. Nur als Hinweis.

2017-02-09 02:00 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  if (mode == true && !StringComplete)        {Wait_for_Start_Character();  HWtoSWSerial();}
Du hast schon Recht es gibt keinen Grund es auszuführen, aber ich habe auch keinen Grund gefunden es zu beenden.
HW to SW Serial ist ja die Kommunikation von Arduino IDE->USB->Arduino Board->WIFiModul. Werden wir später nicht brauchen, aber ich hab es einfach mal drin gelassen, damit man immer vom PC aus Nachrichten an die App schicken kann.

2017-02-09 02:04 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  //Mode "Bidirectional". Just bidirectional Mode between SW and HW Serial.
Sorry das Kommentar ist da falsch (CopyPaste Fehler)

2017-02-09 02:12 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +    if (SerialChar == '[')
okay,  können wir so machen. Wobei ich glaube dass die Zuverlässigkeit/Robustheit gegenüber Fehler unseres Systems steigt, wenn wir Start und End Zeichen haben. 
Wir müssen dann etwas einbauen, damit die WiFly Standard Strings ausgeblendet/ignoriert werden, wie "*HELLO*". Wenn dann natürlich mal die Firmware geändert wird, funktioniert unsere Lösung u. U. nicht mehr.

2017-02-09 02:13 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +// HWtoSWSerial is always active
genau

2017-02-09 02:14 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.h
> +  int StringLength;
okay

2017-02-09 02:16 UTC, myhamidi commented on code/Spikes/Class_WiFiService/Class_WiFiService.ino
> +  myWiFiService.Init(true);
Ja stimmt, es ist eigentlich kein Init sondern eher die standardroutine /task der regelmäßig abläuft. Wie nennt man denn sowas am besten?

2017-02-09 02:16 UTC, myhamidi commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  rxString.reserve(50);
okay

2017-02-09 05:01 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +    if (SerialChar == '[')
Ich stimme zu (mit den Start/Stopp-Zeichen). Wir koennen das auch gerne machen und muessen uns nur entscheiden. Fuer das Android Team scheint es egal zu sein! Auch dien Punkt mit dem ausblenden von den Wifly standard strings stimmt. Lass uns die Diskussion in Slack anstoessen und endgueltig entscheiden ob wir '[' und ']' als Terminierungszeichen wollen.

2017-02-09 05:14 UTC, AlexanderNahr requested changes

2017-02-09 05:14 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/Class_WiFiService.ino
> +  myWiFiService.Init(true);
mhm..also die Routine 1. checked eingehende Nachrichten 2. prozessiert die Strings 3. sendet Nachrihten zurueck. Was hast du sonst noch fuer diese Methode geplant? Wie waere es mit _CommunicationStateMachine_, _ProcessMessages_, _InOutMessages_.

2017-02-09 05:14 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  if (mode == true && !StringComplete)        {Wait_for_Start_Character();  HWtoSWSerial();}
OK, verstanden! Mir war auch nicht bewusst, dass wir SwSerial dann nicht mehr benoetigen!

2017-02-09 05:14 UTC, AlexanderNahr commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +  //Mode "Bidirectional". Just bidirectional Mode between SW and HW Serial.
Echt?  In Zeile 33 wird doch Bidirectional_Mode(); aufgerufen.

2017-02-11 03:07 UTC, AlexanderNahr commented
Da ich den Code am WE fuer die Konfiguration brauche, sollte er noch gemerged werden. Ich sehe keine Bugs/Probleme.

2017-02-11 11:48 UTC, ElBartscho commented on code/Spikes/Class_WiFiService/WiFiService.cpp
> +    if (SerialChar == '[')
Bitte schaut euch meinen Kommentar in Slack dazu an. Ich habe das Gefühl wir drehen uns im puncto Terminierungschars im Kreis.

2017-02-12 18:23 UTC, izabellasandor commented
Ich bin mit euren Anmerkungen auch einverstanden und die Terminierungszeichen "[" und "]" halte ich für sinnvoll (das habe ich aber über Slack auch schon geschrieben). Merge ok von meiner Seite auch.

2017-02-12 20:45 UTC, merged